export const LOAD_COMMENTS = 'LOAD_COMMENTS';

export const IS_COMMENTS_LOADING = 'IS_COMMENTS_LOADING';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const SHOW_COMMENTS = 'SHOW_COMMENTS';
export const ERROR = 'ERROR';
export const COMMENTS_SECTION_EXPANDED = 'COMMENTS_SECTION_EXPANDED';
export const ON_TOGGLE_COMMENTS = 'ON_TOGGLE_COMMENTS';

;